### ISSUE TITLE
Bundle libmaxminddb

### ISSUE THREAD

**Issue by josh** [dbussink/geoip2_compat#1]
Hey @dbussink, question/idea. Is there any reason this gem can't bundle `libmaxminddb` instead of relying on it externally? Would it be ridiculously big?

This is 1 of 2 external gem libs used by github. And we're trying to get `icu` bundled for `charlock_holmes` https://github.com/brianmario/charlock_holmes/pull/82.

wdyt?

/cc @brianmario

**Comment by dbussink** [comment]
It's not a huge library so that should be possible I think. What's the value / goal here? More isolated builds / independent gems?

**Comment by josh** [comment]
Yeah, you won't need to have `libmaxminddb` installed. `gem install geoip2_compat` will pretty much always work.

**Comment by Sami2a** [comment]
require "mkmf"
extension_name = "geoip2_compat"

$LDFLAGS << " #{ENV['LDFLAGS']}"
$CFLAGS << " -std=c99 #{ENV['CFLAGS']}"

RbConfig::MAKEFILE_CONFIG['CC'] = ENV['CC'] if ENV['CC']

$defs << ' -DPACKAGE_VERSION=\"1.0.3\"'

create_makefile("#{extension_name}/#{extension_name}")
